DROP DATABASE IF EXISTS CITYDATABASE;
CREATE DATABASE CITYDATABASE;
USE CITYDATABASE;

DROP TABLE IF EXISTS CITYTABLE;
CREATE TABLE CITYTABLE (
ID INT, COUNTRY VARCHAR(50), CITY VARCHAR(60),
LAT DOUBLE, LON DOUBLE, PRIMARY KEY(ID)
);

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/city_forFinal4.csv' 
                    INTO TABLE CITYTABLE  
                    FIELDS TERMINATED BY ','  
                    ENCLOSED BY '"' 
                    LINES TERMINATED BY '\r\n' 
                    IGNORE 1 ROWS;

SELECT * FROM CITYTABLE;